services:
  api-dev:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vectordb
    command: "uv run fastapi dev src/main.py --host 0.0.0.0 --port 8000"
    profiles: ["dev"]
    networks:
      - app-network
  
  vectordb:
    image: qdrant/qdrant:v1.12.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    networks:
      - app-network

networks:
  app-network:
    driver: bridge